# Generated by Django 2.2.14 on 2020-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='using_place',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
